site_name: My Docs
theme:
  name: material

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - index.md
  - blog01.md
  - blog02.md
  - blog03.md
  - gen_recipes_markdown/r117.md
  - gen_recipes_markdown/r32.md
  - gen_recipes_markdown/r61.md
  - gen_recipes_markdown/r294.md
  - gen_recipes_markdown/r445.md

